import { auth, db } from "./firebase.js";
import { onAuthStateChanged, signOut } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js";
import { collection, doc, getDoc, getDocs, setDoc, addDoc, updateDoc, deleteDoc, query, orderBy, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js";

const $=s=>document.querySelector(s); const view=$("#view"); const toastEl=$("#toast");
const money=n=>`₱${Number(n||0).toLocaleString('en-PH',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const monthKey=()=>new Date().toISOString().slice(0,7); const monthLabel=k=>{const [y,m]=k.split('-');return new Date(Number(y),Number(m)-1,1).toLocaleString('en-US',{month:'long',year:'numeric'})};
let currentUser=null, units=[], records=[], payments=[], settings={internetCost:1000,ownerPercent:70,clientPercent:30,electricity:100,electricityRule:'ADD_TO_CLIENT'}, route='dashboard', search='';
function notify(msg){toastEl.textContent=msg;toastEl.classList.add('show');setTimeout(()=>toastEl.classList.remove('show'),2600)}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function calc(r){const gross=Number(r.grossSales||0), internet=Number(settings.internetCost||0), owner=gross*Number(settings.ownerPercent||0)/100, client=gross*Number(settings.clientPercent||0)/100, elec=Number(settings.electricity||0); const clientTotal=settings.electricityRule==='SUBTRACT_FROM_CLIENT'?client-elec:client+elec; const paid=payments.filter(p=>p.month===r.month&&p.unitId===r.unitId).reduce((a,p)=>a+Number(p.amount||0),0); const due=Math.max(0,clientTotal); const balance=Math.max(0,due-paid); const status=paid>=due&&due>0?'Paid':paid>0?'Partial':'Unpaid'; return {gross,internet,owner,client,elec,clientTotal:due,paid,balance,status}}
async function loadData(){
  const [uSnap,rSnap,pSnap,sSnap]=await Promise.all([getDocs(collection(db,'units')),getDocs(collection(db,'monthlyRecords')),getDocs(collection(db,'payments')),getDoc(doc(db,'settings','business'))]);
  units=uSnap.docs.map(d=>({id:d.id,...d.data()})); records=rSnap.docs.map(d=>({id:d.id,...d.data()})); payments=pSnap.docs.map(d=>({id:d.id,...d.data()})); if(sSnap.exists()) settings={...settings,...sSnap.data()};
}
async function authorize(user){const snap=await getDoc(doc(db,'users',user.uid)); if(!snap.exists()) throw new Error('Your Firebase account is not authorized as an admin.'); const d=snap.data(); if(d.active!==true||d.role!=='admin') throw new Error('Your account is not an active admin.');}
function nav(){document.querySelectorAll('#nav a').forEach(a=>a.classList.toggle('active',a.dataset.route===route));}
function closeMenu(){$('#sidebar').classList.remove('open');$('#overlay').classList.remove('show')}
function render(){nav(); const renderers={dashboard:renderDashboard,units:renderUnits,reports:renderReports,payments:renderPayments,statements:renderStatements,settings:renderSettings}; (renderers[route]||renderDashboard)(); closeMenu(); window.scrollTo({top:0,behavior:'smooth'});}
function baseHead(title,sub,button=''){return `<div class="page-head"><div><h1>${title}</h1><p>${sub}</p></div>${button}</div>`}
function renderDashboard(){
 const month=monthKey(); const rs=records.filter(r=>r.month===month); const rows=units.map(u=>{const r=rs.find(x=>x.unitId===u.id)||{unitId:u.id,month,grossSales:0};return {u,r,c:calc(r)}}); const total=rows.reduce((a,x)=>{a.gross+=x.c.gross;a.owner+=x.c.owner;a.client+=x.c.client;a.elec+=x.c.elec;a.due+=x.c.clientTotal;return a},{gross:0,owner:0,client:0,elec:0,due:0});
 view.innerHTML=baseHead('Dashboard','Overview of all your Piso WiFi units',`<button class="primary-btn" id="addUnitTop">+ Add New Unit</button>`)+
 `<div class="wifi-status"><span class="wifi-dot">●</span><div><strong>Piso WiFi Network</strong><small>Management system connected to Firebase</small></div><span class="online">ONLINE</span></div>
 <div class="kpis"><article class="kpi"><div class="kpi-icon">♙</div><span>Total Units</span><b>${units.length}</b><small>Registered units</small></article><article class="kpi"><div class="kpi-icon">₱</div><span>Total Gross Sales</span><b>${money(total.gross)}</b><small>${monthLabel(month)}</small></article><article class="kpi"><div class="kpi-icon">◉</div><span>Total Internet Cost</span><b>${money(settings.internetCost*units.length)}</b><small>Configured per unit</small></article><article class="kpi green"><div class="kpi-icon">70%</div><span>Owner Share</span><b>${money(total.owner)}</b><small>Based on settings</small></article><article class="kpi purple"><div class="kpi-icon">30%</div><span>Clients' Share</span><b>${money(total.client)}</b><small>Before electricity</small></article><article class="kpi orange"><div class="kpi-icon">⚡</div><span>Total Electricity</span><b>${money(total.elec*units.length?total.elec:0)}</b><small>Configured share</small></article></div>
 <div class="summary-grid"><div class="summary-card report-highlight"><h3>CLIENT AMOUNT DUE</h3><strong>${money(total.due)}</strong><span class="muted">Current month across active units</span></div><div class="summary-card"><h3>PAYMENTS RECEIVED</h3><strong>${money(rows.reduce((a,x)=>a+x.c.paid,0))}</strong><span class="muted">Recorded for ${monthLabel(month)}</span></div><div class="summary-card"><h3>OUTSTANDING BALANCE</h3><strong class="danger-text">${money(rows.reduce((a,x)=>a+x.c.balance,0))}</strong><span class="muted">Amount still to collect</span></div></div>
 <div class="panel"><div class="panel-head"><div><h3>Units / Clients</h3><p>Monthly computation for ${monthLabel(month)}</p></div><div class="tools"><input class="search" id="dashSearch" placeholder="Search client or unit..." value="${esc(search)}"><select id="dashStatus" class="search"><option value="">All statuses</option><option>Paid</option><option>Partial</option><option>Unpaid</option></select></div></div><div class="table-wrap"><table><thead><tr><th>#</th><th>Client / Unit</th><th>Gross Sales</th><th>Internet</th><th>Owner Share</th><th>Client Share</th><th>Electricity</th><th>Client Total</th><th>Status</th><th></th></tr></thead><tbody id="dashBody">${rows.length?rows.map((x,i)=>rowHtml(x,i)).join(''):`<tr><td colspan="10" class="empty">No units found. Add your first unit.</td></tr>`}</tbody></table></div></div>
 <div class="quick-grid"><button class="quick" id="quickUnit"><b>+ Add New Unit</b><span>Create a Piso WiFi unit and client record.</span></button><button class="quick" id="quickReport"><b>▥ Generate Monthly Report</b><span>Review current-month calculations.</span></button><button class="quick" id="quickStatement"><b>▤ Print Statements</b><span>Open client statements and print.</span></button></div>`;
 $('#addUnitTop').onclick=()=>openUnit(); $('#quickUnit').onclick=()=>openUnit(); $('#quickReport').onclick=()=>{location.hash='#reports'}; $('#quickStatement').onclick=()=>{location.hash='#statements'}; $('#dashSearch').oninput=e=>{search=e.target.value; updateDashRows()}; $('#dashStatus').onchange=updateDashRows;
 document.querySelectorAll('[data-view-unit]').forEach(b=>b.onclick=()=>openUnit(b.dataset.viewUnit));
}
function rowHtml(x,i){return `<tr><td>${i+1}</td><td><b>${esc(x.u.name||'Unnamed Client')}</b><br><span class="muted">${esc(x.u.unitCode||x.u.location||'Unit')}</span></td><td class="amount">${money(x.c.gross)}</td><td>${money(x.c.internet)}</td><td>${money(x.c.owner)}</td><td>${money(x.c.client)}</td><td>${money(x.c.elec)}</td><td class="amount">${money(x.c.clientTotal)}</td><td><span class="badge ${x.c.status.toLowerCase()}">${x.c.status}</span></td><td><button class="action-btn" data-view-unit="${x.u.id}">View</button></td></tr>`}
function updateDashRows(){const body=$('#dashBody');if(!body)return; const month=monthKey(), status=$('#dashStatus')?.value||''; const rs=records.filter(r=>r.month===month);let rows=units.map(u=>{const r=rs.find(x=>x.unitId===u.id)||{unitId:u.id,month,grossSales:0};return{u,r,c:calc(r)}}).filter(x=>(!search||`${x.u.name} ${x.u.unitCode} ${x.u.location}`.toLowerCase().includes(search.toLowerCase()))&&(!status||x.c.status===status));body.innerHTML=rows.length?rows.map((x,i)=>rowHtml(x,i)).join(''):`<tr><td colspan="10" class="empty">No matching units.</td></tr>`;document.querySelectorAll('[data-view-unit]').forEach(b=>b.onclick=()=>openUnit(b.dataset.viewUnit))}
function renderUnits(){view.innerHTML=baseHead('Units / Clients','Manage your Piso WiFi machines and associated clients.',`<button class="primary-btn" id="addUnitBtn">+ Add New Unit</button>`)+`<div class="panel"><div class="panel-head"><div><h3>Registered Units</h3><p>${units.length} unit(s) in the system</p></div><div class="tools"><input id="unitSearch" class="search" placeholder="Search client, unit or location..."></div></div><div class="table-wrap"><table><thead><tr><th>Unit</th><th>Client</th><th>Location</th><th>Contact</th><th>Status</th><th>Actions</th></tr></thead><tbody id="unitsBody">${units.length?units.map(u=>`<tr><td><b>${esc(u.unitCode||'—')}</b></td><td>${esc(u.name||'—')}</td><td>${esc(u.location||'—')}</td><td>${esc(u.contact||'—')}</td><td><span class="badge ${u.active!==false?'active':'inactive'}">${u.active!==false?'Active':'Inactive'}</span></td><td><button class="action-btn" data-edit="${u.id}">Edit</button><button class="action-btn danger" data-toggle="${u.id}">${u.active!==false?'Deactivate':'Activate'}</button></td></tr>`).join(''):`<tr><td colspan="6" class="empty">No units yet. Click Add New Unit to begin.</td></tr>`}</tbody></table></div></div>`;$('#addUnitBtn').onclick=()=>openUnit();document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openUnit(b.dataset.edit));document.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=()=>toggleUnit(b.dataset.toggle));$('#unitSearch').oninput=e=>{const q=e.target.value.toLowerCase();document.querySelectorAll('#unitsBody tr').forEach(r=>r.style.display=r.textContent.toLowerCase().includes(q)?'':'none')})}
function renderReports(){const months=[...new Set(records.map(r=>r.month).filter(Boolean))].sort().reverse();const selected=months[0]||monthKey();const summary=reportSummary(selected);view.innerHTML=baseHead('Monthly Reports','Review financial performance by month.',`<div class="tools"><select id="reportMonth" class="search">${[monthKey(),...months].filter((v,i,a)=>a.indexOf(v)===i).map(m=>`<option value="${m}" ${m===selected?'selected':''}>${monthLabel(m)}</option>`).join('')}</select><button class="secondary-btn" id="exportReport">Export CSV</button><button class="primary-btn" id="printReport">Print</button></div>`)+`<div class="summary-grid"><div class="summary-card"><h3>GROSS SALES</h3><strong>${money(summary.gross)}</strong></div><div class="summary-card"><h3>OWNER SHARE</h3><strong>${money(summary.owner)}</strong></div><div class="summary-card"><h3>CLIENT AMOUNT DUE</h3><strong>${money(summary.due)}</strong></div></div><div class="panel"><div class="panel-head"><div><h3>${monthLabel(selected)} — Unit Report</h3><p>Each month is stored separately; prior months are not overwritten.</p></div></div><div class="table-wrap"><table><thead><tr><th>Unit</th><th>Gross Sales</th><th>Internet</th><th>Owner</th><th>Client</th><th>Electricity</th><th>Amount Due</th><th>Paid</th><th>Balance</th><th>Status</th></tr></thead><tbody>${summary.rows.length?summary.rows.map(x=>`<tr><td><b>${esc(x.u.unitCode||'—')}</b><br>${esc(x.u.name||'')}</td><td>${money(x.c.gross)}</td><td>${money(x.c.internet)}</td><td>${money(x.c.owner)}</td><td>${money(x.c.client)}</td><td>${money(x.c.elec)}</td><td>${money(x.c.clientTotal)}</td><td>${money(x.c.paid)}</td><td class="amount">${money(x.c.balance)}</td><td><span class="badge ${x.c.status.toLowerCase()}">${x.c.status}</span></td></tr>`).join(''):`<tr><td colspan="10" class="empty">No monthly records for this month.</td></tr>`}</tbody></table></div></div>`;$('#reportMonth').onchange=e=>renderReportFor(e.target.value);$('#exportReport').onclick=()=>exportCsv(selected,summary.rows);$('#printReport').onclick=()=>window.print()}
function renderReportFor(m){const old=monthKey; const months=[...new Set(records.map(r=>r.month).filter(Boolean))].sort().reverse();const summary=reportSummary(m); const tbody=document.querySelector('.panel tbody');if(tbody)tbody.innerHTML=summary.rows.length?summary.rows.map(x=>`<tr><td><b>${esc(x.u.unitCode||'—')}</b><br>${esc(x.u.name||'')}</td><td>${money(x.c.gross)}</td><td>${money(x.c.internet)}</td><td>${money(x.c.owner)}</td><td>${money(x.c.client)}</td><td>${money(x.c.elec)}</td><td>${money(x.c.clientTotal)}</td><td>${money(x.c.paid)}</td><td>${money(x.c.balance)}</td><td><span class="badge ${x.c.status.toLowerCase()}">${x.c.status}</span></td></tr>`).join(''):`<tr><td colspan="10" class="empty">No monthly records for this month.</td></tr>`}
function reportSummary(month){const rows=units.map(u=>{const r=records.find(x=>x.unitId===u.id&&x.month===month)||{unitId:u.id,month,grossSales:0};return{u,r,c:calc(r)}});return{rows,gross:rows.reduce((a,x)=>a+x.c.gross,0),owner:rows.reduce((a,x)=>a+x.c.owner,0),due:rows.reduce((a,x)=>a+x.c.clientTotal,0)}}
function renderPayments(){view.innerHTML=baseHead('Payments','Record client payments and automatically update balances.',`<button class="primary-btn" id="addPaymentBtn">+ Record Payment</button>`)+`<div class="panel"><div class="panel-head"><div><h3>Payment History</h3><p>All payment entries are retained for reporting.</p></div><div class="tools"><input id="paymentSearch" class="search" placeholder="Search unit or client..."></div></div><div class="table-wrap"><table><thead><tr><th>Date</th><th>Unit / Client</th><th>Month</th><th>Amount</th><th>Method</th><th>Reference</th><th>Notes</th></tr></thead><tbody id="paymentBody">${payments.length?[...payments].sort((a,b)=>String(b.date).localeCompare(String(a.date))).map(p=>{const u=units.find(x=>x.id===p.unitId);return `<tr><td>${esc(p.date||'—')}</td><td><b>${esc(u?.unitCode||'—')}</b><br>${esc(u?.name||'')}</td><td>${p.month?monthLabel(p.month):'—'}</td><td class="amount">${money(p.amount)}</td><td>${esc(p.method||'—')}</td><td>${esc(p.reference||'—')}</td><td>${esc(p.notes||'—')}</td></tr>`}).join(''):`<tr><td colspan="7" class="empty">No payments recorded yet.</td></tr>`}</tbody></table></div></div>`;$('#addPaymentBtn').onclick=()=>openPayment()}
function renderStatements(){view.innerHTML=baseHead('Client Statements','View monthly balances, payment history, and print statements.',`<button class="secondary-btn" id="printStatements">Print</button>`)+`<div class="panel"><div class="panel-head"><div><h3>Client Statements</h3><p>Select a client to view the full monthly statement.</p></div><select id="statementUnit" class="search"><option value="">Select a unit / client</option>${units.map(u=>`<option value="${u.id}">${esc(u.unitCode||'Unit')} — ${esc(u.name||'Client')}</option>`).join('')}</select></div><div id="statementContent"><div class="empty">Choose a client to display their statement.</div></div></div>`;$('#statementUnit').onchange=e=>drawStatement(e.target.value);$('#printStatements').onclick=()=>window.print()}
function drawStatement(id){const u=units.find(x=>x.id===id);const rs=records.filter(r=>r.unitId===id).sort((a,b)=>String(b.month).localeCompare(String(a.month)));if(!u){$('#statementContent').innerHTML='<div class="empty">Choose a client.</div>';return}$('#statementContent').innerHTML=`<div class="settings-card"><h2>${esc(u.name||'Client')} <span class="muted">${esc(u.unitCode||'')}</span></h2><p class="muted">${esc(u.location||'')} · ${esc(u.contact||'')}</p><div class="table-wrap"><table><thead><tr><th>Month</th><th>Gross Sales</th><th>Owner Share</th><th>Client Share</th><th>Electricity</th><th>Amount Due</th><th>Paid</th><th>Balance</th><th>Status</th></tr></thead><tbody>${rs.length?rs.map(r=>{const c=calc(r);return `<tr><td>${monthLabel(r.month)}</td><td>${money(c.gross)}</td><td>${money(c.owner)}</td><td>${money(c.client)}</td><td>${money(c.elec)}</td><td>${money(c.clientTotal)}</td><td>${money(c.paid)}</td><td class="amount">${money(c.balance)}</td><td><span class="badge ${c.status.toLowerCase()}">${c.status}</span></td></tr>`}).join(''):`<tr><td colspan="9" class="empty">No monthly records for this client.</td></tr>`}</tbody></table></div></div>`}
function renderSettings(){view.innerHTML=baseHead('Settings','Configure the business rules used by all calculations.')+`<div class="panel"><div class="settings-card"><h3>Financial Rules</h3><div class="notice">Changes here are used when calculating future and displayed monthly records. Existing records retain their month and sales data.</div><div class="setting-row"><div><b>Internet Cost</b><small>Fixed internet cost per unit, per month.</small></div><input id="sInternet" type="number" min="0" step="0.01" value="${settings.internetCost}"></div><div class="setting-row"><div><b>Owner Share (%)</b><small>Percentage of gross sales allocated to the owner.</small></div><input id="sOwner" type="number" min="0" max="100" step="1" value="${settings.ownerPercent}"></div><div class="setting-row"><div><b>Client Share (%)</b><small>Percentage of gross sales allocated to the client.</small></div><input id="sClient" type="number" min="0" max="100" step="1" value="${settings.clientPercent}"></div><div class="setting-row"><div><b>Electricity</b><small>Configured electricity amount per unit/month.</small></div><input id="sElec" type="number" min="0" step="0.01" value="${settings.electricity}"></div><div class="setting-row"><div><b>Electricity Rule</b><small>Choose whether electricity is added to or subtracted from the client share.</small></div><select id="sRule"><option value="ADD_TO_CLIENT" ${settings.electricityRule==='ADD_TO_CLIENT'?'selected':''}>Add to Client Total</option><option value="SUBTRACT_FROM_CLIENT" ${settings.electricityRule==='SUBTRACT_FROM_CLIENT'?'selected':''}>Subtract from Client Share</option></select></div><div style="display:flex;justify-content:flex-end;margin-top:20px"><button class="primary-btn" id="saveSettings">Save Settings</button></div></div></div>`;$('#saveSettings').onclick=saveSettings}
async function saveSettings(){const owner=Number($('#sOwner').value),client=Number($('#sClient').value);if(owner+client!==100)return notify('Owner + Client share must equal 100%.');settings={internetCost:Number($('#sInternet').value||0),ownerPercent:owner,clientPercent:client,electricity:Number($('#sElec').value||0),electricityRule:$('#sRule').value};await setDoc(doc(db,'settings','business'),settings,{merge:true});notify('Settings saved.');render()}
function openModal(title,body,onSave){$('#modalRoot').innerHTML=`<div class="modal-backdrop" id="backdrop"><div class="modal"><div class="modal-head"><h3>${title}</h3><button class="close" id="closeModal">×</button></div><div class="modal-body">${body}</div><div class="modal-actions"><button class="secondary-btn" id="cancelModal">Cancel</button><button class="primary-btn" id="saveModal">Save</button></div></div></div>`;$('#closeModal').onclick=closeModal;$('#cancelModal').onclick=closeModal;$('#saveModal').onclick=async()=>{try{await onSave();closeModal();await loadData();render();notify('Saved successfully.')}catch(e){notify(e.message||'Unable to save.')}}}
function closeModal(){$('#modalRoot').innerHTML=''}
function openUnit(id=null){const u=id?units.find(x=>x.id===id):null;openModal(id?'Edit Unit':'Add New Unit',`<div class="form-grid"><div class="field"><label>Unit Code *</label><input id="fCode" value="${esc(u?.unitCode||'')}" placeholder="UNIT-001"></div><div class="field"><label>Client Name *</label><input id="fName" value="${esc(u?.name||'')}" placeholder="Client name"></div><div class="field"><label>Location</label><input id="fLocation" value="${esc(u?.location||'')}" placeholder="Location"></div><div class="field"><label>Contact</label><input id="fContact" value="${esc(u?.contact||'')}" placeholder="Contact number"></div><div class="field full"><label>Notes</label><textarea id="fNotes" rows="3">${esc(u?.notes||'')}</textarea></div></div>`,async()=>{const data={unitCode:$('#fCode').value.trim(),name:$('#fName').value.trim(),location:$('#fLocation').value.trim(),contact:$('#fContact').value.trim(),notes:$('#fNotes').value.trim(),active:u?.active!==false};if(!data.unitCode||!data.name)throw new Error('Unit Code and Client Name are required.');if(id)await updateDoc(doc(db,'units',id),data);else await addDoc(collection(db,'units'),{...data,createdAt:serverTimestamp()})})}
async function toggleUnit(id){const u=units.find(x=>x.id===id);if(!u)return;if(!confirm(`${u.active!==false?'Deactivate':'Activate'} ${u.unitCode||u.name}?`))return;await updateDoc(doc(db,'units',id),{active:u.active===false});await loadData();render();notify('Unit status updated.')}
function openPayment(){openModal('Record Payment',`<div class="form-grid"><div class="field full"><label>Unit / Client *</label><select id="pUnit"><option value="">Select unit</option>${units.filter(u=>u.active!==false).map(u=>`<option value="${u.id}">${esc(u.unitCode)} — ${esc(u.name)}</option>`).join('')}</select></div><div class="field"><label>Month *</label><input id="pMonth" type="month" value="${monthKey()}"></div><div class="field"><label>Amount *</label><input id="pAmount" type="number" min="0" step="0.01"></div><div class="field"><label>Date</label><input id="pDate" type="date" value="${new Date().toISOString().slice(0,10)}"></div><div class="field"><label>Method</label><select id="pMethod"><option>Cash</option><option>GCash</option><option>Bank Transfer</option><option>Other</option></select></div><div class="field"><label>Reference</label><input id="pRef"></div><div class="field full"><label>Notes</label><textarea id="pNotes" rows="3"></textarea></div></div>`,async()=>{const unitId=$('#pUnit').value,amount=Number($('#pAmount').value);if(!unitId||!amount)throw new Error('Unit and payment amount are required.');await addDoc(collection(db,'payments'),{unitId,month:$('#pMonth').value,amount,date:$('#pDate').value,method:$('#pMethod').value,reference:$('#pRef').value.trim(),notes:$('#pNotes').value.trim(),createdAt:serverTimestamp()})})}
async function recordSale(id){const u=units.find(x=>x.id===id);const existing=records.find(r=>r.unitId===id&&r.month===monthKey());openModal('Record Monthly Sales',`<div class="notice">${esc(u?.unitCode||'')} — ${esc(u?.name||'')} · ${monthLabel(monthKey())}</div><br><div class="field"><label>Gross Sales *</label><input id="saleGross" type="number" min="0" step="0.01" value="${existing?.grossSales||0}"></div>`,async()=>{const gross=Number($('#saleGross').value);if(gross<0)throw new Error('Gross sales cannot be negative.');const data={unitId:id,month:monthKey(),grossSales:gross,updatedAt:serverTimestamp()};if(existing)await updateDoc(doc(db,'monthlyRecords',existing.id),data);else await addDoc(collection(db,'monthlyRecords'),data)})}
function exportCsv(month,rows){const lines=[['Unit','Client','Gross Sales','Internet Cost','Owner Share','Client Share','Electricity','Amount Due','Paid','Balance','Status'],...rows.map(x=>[x.u.unitCode,x.u.name,x.c.gross,x.c.internet,x.c.owner,x.c.client,x.c.elec,x.c.clientTotal,x.c.paid,x.c.balance,x.c.status])];const blob=new Blob([lines.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n')],{type:'text/csv'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`piso-wifi-report-${month}.csv`;a.click();URL.revokeObjectURL(a.href)}

document.addEventListener('click',e=>{const b=e.target.closest('[data-route]');if(b){e.preventDefault();location.hash='#'+b.dataset.route}});
window.addEventListener('hashchange',()=>{route=(location.hash.replace('#','')||'dashboard');render()});
$('#menuBtn').onclick=()=>{$('#sidebar').classList.add('open');$('#overlay').classList.add('show')};$('#overlay').onclick=closeMenu;$('#logoutBtn').onclick=async()=>{await signOut(auth);location.href='index.html'};

function showAuthError(message){
  console.error('[PISO WIFI]', message);
  const loader=$('#authLoading');
  if(loader){loader.innerHTML=`<div style="max-width:560px;text-align:center;padding:28px;background:#fff;border:1px solid #e5e7eb;border-radius:18px;box-shadow:0 12px 40px rgba(15,23,42,.10)"><strong style="display:block;font-size:20px;color:#17243A;margin-bottom:10px">Unable to open the dashboard</strong><span style="display:block;color:#64748B;line-height:1.6">${esc(message)}</span><button onclick="location.href='index.html'" style="margin-top:18px;padding:11px 18px;border:0;border-radius:10px;background:#1685F5;color:#fff;font-weight:700;cursor:pointer">Return to Login</button></div>`;
    loader.classList.remove('hidden');
  }
}

async function bootstrap(user){
  if(!user){ location.replace('index.html'); return; }
  currentUser=user;
  try{
    await authorize(user);
    await loadData();
    $('#authLoading').classList.add('hidden');
    $('#app').classList.remove('hidden');
    $('#userEmail').textContent=user.email||'Admin';
    $('#currentMonthChip').textContent=monthLabel(monthKey());
    route=location.hash.replace('#','')||'dashboard';
    render();
  }catch(e){
    showAuthError(e?.message || 'Firebase authorization or database access failed.');
  }
}

let authResolved=false;
const authTimeout=setTimeout(()=>{
  if(!authResolved){
    const u=auth.currentUser;
    if(u) bootstrap(u);
    else showAuthError('Firebase Authentication did not finish loading. Please refresh the page and try logging in again.');
  }
},8000);

onAuthStateChanged(auth,user=>{
  authResolved=true;
  clearTimeout(authTimeout);
  bootstrap(user);
});
